### ISSUE TITLE
Specific Python 3 environment

### ISSUE THREAD

**Issue by 27182812** [behavioral-data/PARTNER#2]
Could you tell me the specific Python 3 environment, Because many extension versions do not match. Thank you!

**Comment by ash-shar** [comment]
Thank you for your interest!

You may find the requirements.txt file helpful as it has details on the modules we are using. The modules can be installed using:

`pip install -r requirements.txt`  

I also recommend checking out the [DialoGPT repo](https://github.com/microsoft/DialoGPT) on which our code is based.

Let me know if you still face any issues. Thanks!
